packages:
  - 'apps/*'
  - 'apps/api/node_modules'
  - 'apps/web/node_modules'
  - 'packages/*'

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  bcrypt: true
  prisma: true
  '@prisma/client': true
  '@prisma/engines': true
  '@nestjs/core': true
